# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4be904a0a36e59bb638ca57d2009b065c93f655dba4e6c4b415f08d09b3a79b01a6f4f389ad519ab0f0e206f57ab6cd282c8fb260ee9187e8f8ee4a488635604

test:
  secret_key_base: f4d2da867280eee57ab12767382a8aa3e92b2aa9cf2fe96a9a8137aa6c2723fe28add7d0d747ae34ea6cf5bebd0bf7084c8e6a3404fe62b3a5a6cbf31faa2c86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
